name: pipeline-basico

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executa comando
        run: echo "Configuração inicial do pipeline"

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Espera por aprovação manual
        uses: hmarr/auto-approve-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Aguardando aprovação manual para continuar..."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy para AWS S3
        run: |
          echo "Iniciando deployment no AWS S3..."
          aws s3 cp ./build/ s3://meu-bucket/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
